### ISSUE TITLE
Create regexp object once rather than each time in func Less

### ISSUE THREAD

**Issue by cgilling** [skarademir/naturalsort#4]
Hey, I was looking over your code and saw that you are compiling a new regexp object every time Less is called. Seems like this could be a lot of overhead especially if you are doing a lot of sorting.

I would recommend doing something like this in global scope and then just use it instead of `r` in the `Less` function. `regexp.Regexp` is safe for concurrent use.

``` go
var reg = regexp.MustCompilePOSIX(`^([^0-9]*)+|[0-9]+`)
```

**Comment by skarademir** [comment]
**Before**

```
BenchmarkSort      50000         41224 ns/op
ok      github.com/skarademir/naturalsort   2.484s
```

**After**

```
BenchmarkSort     100000         20460 ns/op
ok      github.com/skarademir/naturalsort   2.263s
```
