### ISSUE TITLE
RegEx Problem

### ISSUE THREAD

**Issue by johnrs** [skarademir/naturalsort#5]
Perhaps I'm not quite understanding, but I believe that the regular expression isn't working all the time.  Consider these test cases:
    []string{"1a10", "1ax2", "1ax"}
    []string{"z1a10", "z1ax2", "z1ax"}
I believe that changing the RegEx to this works:
    r := regexp.MustCompilePOSIX(`[^0-9]+|[0-9]+`)

**Comment by skarademir** [comment]
Fixed.

Thanks!
