### ISSUE TITLE
Some of test cases fail

### ISSUE THREAD

**Issue by xlab** [skarademir/naturalsort#8]
```
Compared a0001 to a0000001: expected LESS
Compared a01b001 to a001b01: expected LESS
```

I wonder if fixing this will knock the performance to zero :skull:

**Comment by johnrs** [comment]
Putting
    if inti == intj {
        return len(spliti[index]) < len(splitj[index])
    }

in front of
    return inti < intj

seems to fix it.

**Comment by xlab** [comment]
I confirm.
